version: '3.8'

services:
  redis:
    image: redis
    restart: unless-stopped

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - database:/var/lib/postgresql/data

  backend:
    image: backend
    environment:
      - FRONT_URL=http://localhost:5000
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_HOST=db
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db

  frontend:
    image: frontend
    environment:
      - API_URL=http://localhost:8000
    ports:
      - 5000:5000

volumes:
  database:


