version: '3.8'

services:
  back:
    image: backend
    environment:
      - FRONT_URL=http://localhost:5000
    volumes:
      - ./logs.txt:/backend/logs.txt
    ports:
      - 8000:8000

  front:
    image: frontend
    environment:
      - API_URL=http://localhost:8000
    ports:
      - 5000:5000

