# FRONTEND DOCKERFILE

FROM ubuntu:16.04

WORKDIR /frontend
COPY . ./

RUN apt-get update
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash
RUN apt install -y nodejs

RUN npm install && npm audit fix
ENV API_URL=http://localhost:8000

CMD ["npm", "start"]

