version: '3.8'

# NOTE: This file is based on the one created for exercise 2.8 - thus, a locally bound database is not configured - see ex_2-9 for how I did that.

services:
  redis:
    image: redis
    restart: unless-stopped

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - database:/var/lib/postgresql/data

  backend:
    image: backend
    environment:
      - FRONT_URL=http://localhost
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_HOST=db
    depends_on:
      - redis
      - db

  frontend:
    image: frontend
    environment:
      - API_URL=http://localhost/api/

  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend

volumes:
  database:

